# Dataframes and data handling

Dataframes are tabular data structures with labeled axes (rows and columns, like in excel). These data structures are commonly used in data science using software libraries such as Pandas and R data frames (a reminder for those familiar with R).

Here we will use [pandas](https://pandas.pydata.org/docs/). Find a cheat sheet [here](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf) 

First, we will import two libraries: `pandas` and `numpy`

In [10]:
import pandas as pd
import numpy as np

First, let's define a simple example data frame with 100 rows and two columns with random variables.

In [2]:
num_rows = 1000
random_data_1 = np.random.normal(loc=2, scale=1, size=num_rows)
random_data_2 = np.random.normal(loc=0, scale=1, size=num_rows)

In [3]:
len(random_data_1)

1000

Then we create a **dictionary** (data structure representing a collection of variables of any type) with the two data lists.

In [4]:
data = {'Random variable 1': random_data_1,
        'Random variable 2': random_data_2
        }
data

{'Random variable 1': array([ 1.689681  ,  0.95345704,  2.55195419,  3.69338697,  1.98360653,
         1.64641677,  0.93666913,  1.48483987,  1.65937141,  2.30141412,
         3.28646403,  2.71586542,  1.68493967,  3.15102411,  3.15398771,
         4.31659354,  1.35061766,  3.24559725,  0.48235518,  2.50490334,
         2.30049471,  1.9231015 ,  2.68495064,  3.77361289,  1.55478788,
         1.49216143,  1.04147836,  2.46481002,  1.85441319,  3.49501921,
         3.30998585,  0.92930278,  2.43823093,  0.96000508,  2.65457126,
         1.97922352,  0.89995923,  0.52563386,  2.37667673,  1.58004155,
         3.28468044,  1.7873629 ,  2.18991032,  2.43932325,  1.06886106,
         1.17223085,  2.62096181,  1.97668362,  1.91975723,  3.32060971,
         2.5338865 ,  1.0570152 ,  2.17001733,  1.51391682,  1.46689863,
         2.09067336,  2.15528942, -0.07549357,  3.10000175,  1.96369331,
         2.09982678,  0.26611104,  2.24634956,  2.27462419,  1.97188829,
         1.41703061,  1.68812381,  1.81193069,  1.16316219,  2.37112431,
        -0.10292472,  2.07492368,  3.41556361,  3.77658552,  2.43649056,
         2.47777813,  1.9252548 , -0.05394957,  2.3820525 , -0.36761964,
        -0.58980633,  2.40455823,  1.18684736,  2.17702497,  1.47271076,
         1.38229629,  0.41091556,  1.27474751,  1.92063156,  1.82419995,
         2.74307132,  1.62936324,  3.1459797 ,  0.57535276,  1.70539269,
         2.86294491,  1.20385068,  1.46139941,  1.74179798,  1.91594211,
         2.18313561,  1.73291728,  1.24088645,  0.92158897,  1.49858145,
         0.19922381,  2.71970639,  1.78244722,  1.88209936,  2.52534568,
         0.2013538 ,  1.23458189,  1.33360601,  3.59712689,  1.68956082,
         0.97676089,  3.14744507,  2.44638332,  1.15965413,  2.02982658,
         0.8559234 ,  1.71664805,  1.98677923,  2.16669674,  1.07879927,
         2.59595225,  0.0747295 ,  4.0427776 ,  2.33397419,  3.37856578,
         1.08664139,  1.94540547,  1.3067886 ,  1.95073698,  2.93837886,
         1.66897645,  2.60007601,  2.00407989,  1.97826597,  3.41701162,
         0.786302  ,  3.17942654,  2.32141854,  3.21075815,  1.77012259,
         1.24613156, -1.57103514,  1.00529288,  2.04463235,  2.2014988 ,
         2.46214277,  2.22410003,  2.12421471,  1.00765346,  1.82509665,
         1.87835158,  2.60897913,  1.12842004,  2.06168571,  2.9221072 ,
         1.79724894,  0.47825479,  3.83356973,  1.50443904,  0.49832119,
         1.92970565,  1.67268744,  1.63235838,  0.06679715,  2.38405233,
         1.67077298,  2.1967233 ,  2.70065603,  1.77047558,  1.34683693,
         1.61598987,  2.39742299,  1.24952193,  2.40530174,  3.27659384,
         2.30753685,  1.02263741,  2.19811648,  0.75439925,  1.20670746,
         1.63798203,  1.26758388,  1.75800874,  1.53184348,  2.92068994,
         1.03495523,  2.29979441,  1.87381945,  2.48456408,  0.88091046,
         1.11554922,  2.05644117,  1.78889425,  1.84011923,  1.8792146 ,
         1.24470746,  1.2609484 ,  4.33660367,  3.29265843,  2.15498548,
         2.18321727,  1.34376957,  3.19477139,  1.65194968,  1.21718739,
         1.11733095,  3.80055764,  1.57921321,  1.25013275,  3.06600584,
         1.82935158,  2.27507075,  0.9777814 ,  1.39352732,  2.90346893,
         1.22565771,  2.23833661,  3.11374238,  1.25914266,  1.15559867,
         1.48149877,  1.37081555,  2.39860202,  2.33261205,  1.79509739,
         0.70894267,  1.40208849,  0.85945222,  1.25911707,  2.64499106,
         3.0699198 ,  1.37081625,  2.82701919,  3.93766783,  0.80916729,
         2.811331  ,  1.44429835,  1.33856867,  3.1942582 ,  2.93156037,
         2.21390158,  2.07499446,  3.96644302,  2.47074012,  2.83886972,
         2.92220236,  3.21623023,  3.70465106,  2.23076302,  1.62277629,
         3.92517059,  0.50626894,  4.28853034,  2.06592999,  1.32224293,
         0.91354206,  2.42307438,  1.2798797 ,  3.5685662 , -0.89040736,
         0.60346911,  1.14152198,  1.7540408 ,  1.91494449,  2.14875347,
         1.98392771,  1.5919211 ,  3.1282008 ,  1.21772405,  0.52717694,
         1.26600758,  3.32264041,  1.84646226,  1.79577426,  2.54061941,
         2.61734068,  3.31853829,  1.53301947,  3.09177346,  0.1611545 ,
         4.2938882 ,  1.88417622,  2.19623719,  1.21070284,  2.09415493,
         2.80034793,  0.97060803,  2.83814785,  3.35343767,  1.32699032,
         2.55744405,  2.88031158,  1.80908876,  4.27922038,  1.1654725 ,
         1.92628061,  0.73352685, -0.70074081,  2.82636529,  3.40428596,
         1.45607861,  2.16533679,  2.1562491 ,  1.91941477,  1.50030163,
         1.96232587,  1.89033028,  1.91754849,  3.68291372,  1.76503088,
         2.80857192,  2.75030294,  2.88011726,  2.48526075,  2.87916795,
         0.17584008,  2.7441716 ,  3.19624581, -0.50887595,  2.01738089,
         2.02028329,  1.23179273,  2.68529788,  0.22972184,  1.76989971,
         0.85870822,  2.4464025 ,  1.19831639,  1.67624619,  1.21631738,
         1.26412943,  1.14595625,  3.73564992,  1.73531887,  2.21544237,
         1.72078955,  1.82551358,  2.35883603,  3.34667254,  2.67893329,
         3.08112716,  3.1661658 ,  3.29678656,  1.52144639,  1.9342532 ,
         4.36503363,  2.84997952,  2.88386387,  0.67861954,  0.49304302,
         1.77626348,  3.9334595 ,  3.11100954,  2.37203632,  2.78475839,
         3.58436298,  3.03437441,  3.34372955,  1.49837458,  2.17487938,
         0.99544931,  1.18805812,  2.11672024,  1.9257334 ,  2.6738621 ,
         2.94945403,  1.82520146,  2.31601834,  2.42591191,  1.56925267,
         2.09291423,  2.04400347,  2.14914139,  1.39295147,  2.57786152,
         2.00808674,  0.75033579,  1.497776  ,  2.71494649,  2.98876479,
         1.47652493,  1.7026443 ,  0.93724803,  1.82730044,  2.31001729,
         2.92742767,  1.61266956,  2.43194827,  2.24814553,  1.24238614,
         2.85002513,  2.71500129,  1.8285139 ,  2.2204864 ,  1.13640563,
         3.53475832,  1.41951238,  1.3007891 ,  3.30522539,  1.98318908,
         2.57852375,  2.78312154,  2.77863414,  1.47162553,  2.19426175,
         2.53913084,  3.19116792,  2.39340944,  2.20517729,  1.97684742,
         1.81815518,  1.26438917,  1.98324485,  2.44289437,  3.18253853,
         1.06229255,  1.1632346 ,  2.80243357,  2.99516923,  0.48402293,
         1.64799312,  0.41584086,  1.14904348,  2.0371052 ,  1.07491151,
         0.95793821,  2.21328206,  2.22335556,  1.64578943,  1.65773992,
         2.77036218,  1.08356736,  0.538911  ,  3.96301611,  1.65644463,
         2.0741629 ,  1.76369867,  1.76803336,  2.2595239 ,  3.04094906,
         1.15390323, -0.2930824 ,  1.1730898 ,  2.17505667,  2.62748355,
         3.60692699,  1.88702232,  0.5916889 ,  2.9801928 ,  0.77648171,
         2.11239748,  2.79242419,  2.18770958,  2.81500358,  2.96052961,
         2.30947051,  2.65074414,  2.70045076,  1.45388518,  2.09708267,
         1.83449085,  0.54434327,  2.78721302,  2.16951281,  0.88153091,
         1.91592797, -0.45577062,  1.86010281,  2.24769823,  3.22075383,
         4.41961432,  2.02912783,  2.45613432,  0.81544825,  2.61959436,
         0.61315995,  1.85443067,  1.71516742,  2.74014841,  1.76657193,
         2.53048535,  2.12664951,  2.07302979,  0.50296116,  1.46348769,
         3.00263879,  0.6359608 ,  1.0547623 ,  1.66884253,  4.3916903 ,
         2.75617136,  3.12524221,  0.14990142,  1.80432568,  2.3198402 ,
         4.07841859,  1.24265756,  1.0701095 ,  3.2948505 ,  0.83280187,
         1.69908476,  2.69883999,  1.62822092,  2.1360054 ,  1.7995764 ,
         2.29433713,  1.84409357,  2.10794001,  2.28825297,  0.99727844,
         2.22063478,  3.70862866,  1.69024491,  2.15857446,  0.78163947,
         2.1080757 ,  4.16657498,  0.87633276,  2.60313374,  3.71149777,
         3.32489237,  2.01767251,  1.54093209,  2.22468844,  2.81909332,
         1.83929977,  2.56967244,  3.67230234,  2.5098835 ,  3.07313617,
         1.33028756,  1.7254113 ,  2.2629264 ,  2.64925351,  2.22576197,
         0.81955584,  2.71800086,  2.37881046,  1.45339056,  3.67343848,
         2.77372456,  1.21248194,  0.85555239,  1.83188273,  4.57039061,
         1.66000324,  1.71045341,  1.53365071,  3.41733533,  1.69080636,
         2.41184944,  1.83973172,  1.32046932,  1.31727772,  1.53850191,
         1.79982609,  3.08843334,  0.66176116,  2.71022126,  1.76366204,
         1.4410617 ,  0.90839648,  2.81535251,  2.41133654,  2.24753929,
         0.59770088,  2.87485974,  2.27871487,  2.53482544,  2.72974461,
         2.1598439 ,  2.90485369,  2.71335559,  2.66742121,  2.92149846,
         2.16171786,  3.0011615 ,  3.68345071,  1.83198743,  0.91928526,
         2.31983383,  1.24424943,  3.13964878,  1.87657678,  0.67893067,
         1.57309605,  2.37341842,  1.48156769,  3.18074384,  3.3546288 ,
         0.47200836,  2.66146804,  1.23444642,  2.90208372,  2.65961477,
         3.00076112,  1.22352265,  1.16531049,  2.97262394,  0.78789429,
         2.19370033,  1.24109922,  1.33384461,  3.3315982 ,  3.44789043,
         3.5047405 ,  1.69432749,  2.24565577,  1.86716297,  3.30519565,
         3.28714886,  1.90220623,  1.64844838,  0.85931975,  1.91439028,
        -0.50174829,  2.05308391,  1.66747254,  1.06645001,  2.06460453,
         2.095555  ,  0.88373914,  1.82902819,  1.95381443,  1.7904134 ,
         2.27341117,  4.17322846,  2.34355092,  1.98329794,  0.86202393,
         1.81593305,  2.51735877,  3.8076097 ,  2.1417721 ,  1.43095372,
         1.67027595,  0.38637632,  1.002288  ,  2.2053342 ,  2.43191977,
         2.41289539,  0.57010671,  1.66617904,  0.03920437,  1.62338749,
         2.41570238,  1.29848076,  2.11463028,  1.90809404,  1.89812562,
         2.29812125,  1.74029522,  2.84187391,  1.89458059,  3.20062363,
         1.13733265,  1.260836  ,  2.5042012 ,  4.58703037,  1.40345977,
         2.81789551,  3.31590969,  2.50421252,  0.1280426 ,  0.68382895,
         1.54970899,  1.26011077,  0.50066012,  1.62628238,  2.68784065,
         1.56813378,  1.10309238,  1.17513232,  3.25298741,  1.80732675,
         1.88581695,  3.85044157,  2.34804426,  1.65983282,  2.68537444,
         2.36474392,  1.47271137,  2.96869852,  2.09729206,  0.85582624,
         2.21654714,  3.15915729,  2.45547271,  0.29619073,  0.85410638,
         1.90733602,  2.39143574,  3.66592594,  2.17810294,  1.81006001,
         0.35717498,  0.51204972,  1.52539352,  0.59143274,  1.90996   ,
         2.02601269,  1.49146296,  3.24531679,  2.21468135,  1.33712778,
         2.79168938,  1.86102782,  2.64132483,  3.17950025,  2.8050636 ,
        -0.23458623,  4.3712705 ,  0.75377259,  0.93035999,  1.17505679,
         0.56561173,  1.20817498,  2.49234699,  1.25637666,  2.7959762 ,
         1.30644019,  3.71652952,  3.63811934,  1.3600649 ,  0.61335083,
         3.69773777,  3.14425705,  1.08946734,  3.28584971,  2.2171807 ,
         2.59468954,  2.31419021,  2.38027422,  3.50261982,  3.47770646,
         3.39412999,  1.335906  ,  0.54385035,  2.80296479,  2.24539111,
         1.88894522,  3.37853138,  3.4683519 ,  0.08352665,  1.70750582,
         0.65110533,  2.16124613,  1.91077964,  1.18463427,  1.28950083,
         1.65746257,  1.6137918 ,  2.57132322,  1.64894585,  3.95829782,
         1.79737787,  0.23243149,  2.68793691,  3.62920575,  1.6774804 ,
         2.07379858,  3.92260129,  3.04434872,  2.44952492,  2.32667365,
         0.43575567,  2.62015012,  3.3856055 ,  2.99564095,  2.1849722 ,
         1.89836018,  4.55693093,  2.04613703,  1.21416524,  2.48623302,
         2.73205333,  1.90792972,  1.20433643,  2.33950792,  0.96630711,
         2.18921497,  2.40092408,  1.225499  ,  0.09550894,  2.41695103,
         3.24675211,  3.6188271 ,  1.37568973,  1.88284316,  3.08013028,
         2.54343244,  1.31451774,  1.68851508,  1.69491396,  0.97293302,
         3.25379734,  2.77756399,  3.84588216,  2.69020715,  2.91987987,
         2.25033181,  1.92615565,  2.22261147,  3.61221779,  1.44090907,
         2.90149549, -0.29376606,  0.30796427,  1.64110232,  2.34905767,
         2.18882162,  1.95659712,  2.72986141,  0.48746879,  0.93413643,
        -0.14806988,  2.78067125,  1.42319067,  2.64687222,  1.64987094,
         1.94468885,  1.22459975,  4.26227693,  1.96788062,  1.53795723,
         2.51135014,  2.51761031,  0.97865711,  3.00578795,  1.78890714,
         3.83459175,  2.09069742,  0.78892308,  1.49239521,  3.29202697,
         1.82554213,  0.94305257,  2.7932477 ,  2.38336718,  4.60413226,
         2.0869404 ,  3.11593444,  2.23784166,  2.59508727,  0.91442888,
         1.13851004,  1.96810793,  3.28942511,  1.36162169,  2.4157546 ,
         0.8991063 ,  2.02199159,  1.66504313,  0.58945277,  4.55255837,
         1.21294322,  2.26312882,  1.36682724,  3.22032128,  0.88011922,
         1.75595909,  1.60970668,  1.69971163,  1.90934961,  0.9482135 ,
         1.45817253,  2.17166523,  2.6431451 ,  1.45723081,  0.78570389,
         1.40231715,  1.99994708,  2.20535699,  1.49852894,  2.36260201,
         0.90425039,  3.32592042,  1.8330791 ,  2.38143177,  2.75803069,
         2.97208107,  2.4106896 ,  2.13983488,  3.53642561,  2.19795079,
         1.10525334,  0.69503492,  1.48309216,  1.71052262,  2.81359764,
         1.28947109,  0.32451871,  1.59264389,  2.50031615,  2.604339  ,
         1.69119074,  3.23850905,  2.0770842 ,  0.64262249,  2.62198132,
         3.24468713,  3.79215608,  3.25370479,  1.17009135,  2.70334865,
         1.11758174,  1.25341429,  2.10086122,  1.96433325,  2.86864008,
         1.17775956,  0.54594195,  0.22717524,  2.88104962,  3.03242018,
         3.78867703,  1.24601678,  2.63807107,  0.74818605,  2.87036959,
         2.23287448,  1.68189696,  0.7647873 ,  2.52774866,  3.27477819,
         3.54120322,  1.93187093,  3.55125632,  1.20521645,  0.80258783,
         2.88391704,  2.02740986,  2.78711907,  0.40378708,  2.44058906,
         0.49694455,  1.28166865,  3.17161411,  1.76857678,  1.98405574,
         1.91904461,  2.6367568 ,  2.04748299,  3.4175029 ,  2.92369187,
         1.88580236,  2.56934992,  2.1737907 ,  2.15939362,  3.87683517,
         1.97710013,  2.81227272,  1.52979133,  2.10557416,  2.18364314,
         1.36912968,  2.49746933,  3.3069723 ,  2.27756611,  0.81445514,
         2.37243072,  2.71162144,  2.44229332,  2.32925316,  2.35455257,
         3.94219426,  2.26638999,  2.63722967,  2.20433177,  3.6041833 ,
         2.48562905,  0.01256014,  2.13761966,  3.30104238,  3.97088643,
         2.51834058,  1.60376125, -0.11470401,  1.06487597,  2.75429841,
         1.92105645,  2.24757378,  2.34655377,  2.38506893,  2.09028741,
         2.30148246,  1.32673312,  0.84166411,  2.19639028,  2.01909769,
         2.72055825,  1.87461173,  2.27358195,  3.09952585,  2.34802456]),
 'Random variable 2': array([-3.73315819e-01,  7.39979750e-01, -1.48326258e+00,  9.18401847e-01,
         1.26400316e+00,  5.71562126e-01,  2.42876716e-02,  1.21994076e-02,
        -2.16694152e+00, -5.71198468e-01, -1.47480596e+00, -5.76564903e-01,
         4.05586837e-02, -1.90688508e+00, -1.82852469e+00, -9.05755335e-02,
        -4.25836874e-01, -8.92311378e-01, -1.33332193e+00, -7.85952545e-01,
         5.88560342e-01, -3.15537557e-01,  8.92181968e-01, -5.21679381e-01,
         4.17307551e-01,  1.54403661e+00, -2.96821066e+00,  1.71161577e+00,
         8.79540169e-01, -7.85134133e-01, -4.54920226e-02,  2.39580132e-01,
         7.50762178e-01,  1.22535549e+00,  1.74067241e+00, -2.44904328e-01,
        -6.29479904e-01,  6.68920440e-01, -1.30076023e+00,  1.34308250e+00,
         1.85373417e+00,  2.83341875e-01, -3.81936388e-01, -1.52415799e+00,
         1.73060498e+00, -2.04556029e+00,  1.39478725e+00,  6.24877721e-01,
         9.78009757e-01, -1.05934764e+00, -1.44124688e+00, -9.90043332e-01,
        -6.60060772e-01, -1.00950363e+00, -1.21209978e+00,  1.94495488e-01,
         9.04023605e-01,  1.22568815e+00, -5.45066021e-01, -6.89972920e-01,
         3.13836011e-02,  5.47091264e-01,  1.20238151e+00,  1.66947095e-02,
        -2.38599017e-01,  3.89725263e-01, -1.67378466e+00,  2.85023531e-01,
        -2.23756309e-01,  9.89140330e-01, -6.72146728e-01, -9.75176798e-01,
         1.43159754e-01,  1.43918918e+00, -1.17017785e+00, -9.17603167e-01,
         1.36644736e-01,  6.12085035e-02,  3.50384102e-01, -1.09654547e+00,
        -4.74109899e-01, -5.60266168e-01,  8.07154674e-02,  2.94872659e-01,
        -2.05750016e-01, -5.19477064e-01,  2.67151593e-01, -9.45412632e-01,
         2.50628424e-01, -7.87408761e-01, -6.68510953e-01,  1.45598980e+00,
         4.51651186e-01, -2.83952005e-01, -1.03522493e-02,  1.36894604e+00,
        -5.97279680e-01, -1.02151063e+00,  3.74223259e-01, -2.20688765e-01,
         8.68008990e-01, -3.40372806e-01, -1.73421011e+00,  8.28264387e-01,
        -1.87628168e+00,  8.98091347e-01,  7.90977145e-01, -1.94025095e+00,
        -3.18758308e-01,  1.93243384e+00,  1.08283949e-02,  7.49332485e-02,
         1.28016923e+00, -7.42182994e-01,  1.50881771e+00, -8.62041281e-01,
        -2.32359357e-02,  5.16483343e-01, -4.38568315e-01, -2.04491244e+00,
        -9.05569164e-01, -1.32088202e+00, -5.63198510e-01, -1.08748741e+00,
         6.34305002e-01, -1.94707178e-01,  2.05963915e+00,  2.81134499e-01,
         1.42394398e+00, -8.87893838e-01, -1.17172994e+00,  1.04518841e+00,
        -1.24692758e+00, -4.28928848e-01,  7.22433733e-01,  1.53068291e-01,
         9.04971551e-01, -5.49757727e-02,  1.61061244e+00, -8.95764262e-01,
         1.45883186e+00, -4.10386387e-01,  1.03747556e+00, -1.42963181e-01,
         1.18246023e+00,  1.40650963e+00,  7.55924322e-01,  1.06594597e+00,
        -1.70852837e-01, -6.20607609e-01,  4.30986700e-01,  3.60256336e-01,
         3.91166116e-01,  1.41405113e+00,  9.37530492e-01, -4.69006019e-01,
        -1.03637242e+00,  1.03269192e+00,  2.67310972e-02,  5.92718483e-01,
         1.45743048e+00,  8.30692738e-01,  1.37090283e-01, -1.35131111e+00,
         1.69010099e+00, -8.55095838e-01, -9.27306042e-01, -4.83463312e-01,
         3.25369032e-01,  6.52276687e-01, -9.84759927e-01, -5.61725016e-02,
        -1.28837715e+00,  1.19146503e+00,  8.45075375e-01,  1.07506855e+00,
        -1.29298816e+00, -5.91013835e-01,  5.67133881e-01,  1.68703457e+00,
        -3.79294473e-01,  4.51492942e-01,  9.21846917e-01, -2.50346940e+00,
         1.66740432e+00, -2.14456480e+00, -5.59118067e-01,  1.20072234e+00,
        -2.66271365e-01, -2.34002918e-01,  5.90040159e-01, -1.39370667e+00,
        -2.48469812e+00,  1.86320684e+00, -5.39703055e-02,  2.16325112e+00,
         3.85666439e-01, -9.17637422e-01, -1.07631779e-01,  1.77873696e+00,
         1.07989687e+00,  8.85207160e-01,  2.05239033e-01,  3.10267005e-01,
         4.99613419e-01, -4.20295340e-02,  9.39038643e-01,  4.93066775e-02,
        -2.63332919e+00, -1.62399570e+00,  6.64393351e-01, -7.34943326e-01,
         1.01222832e+00, -7.06108502e-01, -3.18524785e-01,  6.30911155e-01,
        -2.77069151e-01, -3.43209117e-01, -1.43646529e-02,  9.32487643e-02,
        -4.33576732e-01,  5.26431879e-01,  6.19139413e-01, -2.05316024e-01,
         3.54955204e-01, -1.27771590e+00, -1.32913380e+00,  4.13265702e-01,
         1.91090548e+00, -5.96006857e-01,  2.45744888e-01,  3.27385414e-01,
         1.54436413e-01, -3.24078205e-01, -6.42162652e-01, -8.13727749e-01,
        -6.27318006e-01,  9.43085792e-01,  8.35623734e-01, -1.02579998e-01,
        -1.10309818e+00,  7.65479215e-01, -5.69319917e-01,  2.41271592e-01,
        -2.90679130e-01,  2.75055825e+00,  4.23528620e-03, -8.55273527e-02,
        -7.86404767e-01, -1.45802207e+00, -5.59849224e-01,  1.66392402e-01,
         1.35646861e+00, -1.21032815e+00, -8.26884379e-01, -7.40972109e-01,
        -4.46761939e-01, -2.75629769e-01,  8.36730867e-01, -1.35368954e+00,
         1.58811162e-01, -1.43089382e+00, -9.20961325e-01,  7.90728369e-01,
         2.86632183e-01, -2.61346535e-01,  1.22760398e+00, -7.85706954e-01,
         1.39250830e+00, -7.11999086e-02, -1.63209805e+00,  3.50050989e-01,
         2.22874818e-01,  5.83871921e-01,  3.38685304e-01,  1.36870764e+00,
        -9.13781827e-01,  5.99419177e-01, -1.26598709e+00,  6.26284221e-01,

In the dictionary, we now have two lists of numbers. 

With the `DataFrame` function from pandas (here integrated with the abbreviation `pd`), we can convert the dictionary into a data frame.

In [5]:
df = pd.DataFrame(data)
df

     Random variable 1  Random variable 2
0             1.689681          -0.373316
1             0.953457           0.739980
2             2.551954          -1.483263
3             3.693387           0.918402
4             1.983607           1.264003
..                 ...                ...
995           2.720558           0.415682
996           1.874612           0.341780
997           2.273582           0.032220
998           3.099526          -0.043344
999           2.348025           1.753431

[1000 rows x 2 columns]

In the output here, we can now see the tabular structure of the data frame. 

In addition, pandas include multiple functions that can be directly applied to a data frame:

`info()` returns a quick summary of the values with essential information that is included in the data frame. 

`corr()` returns a correlation matrix that informs about the similarities between variables (i.e., a high correlation r > .8 would indicate that two variables would be highly similar; an r around zero would indicate low similarity).

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Random variable 1  1000 non-null   float64
 1   Random variable 2  1000 non-null   float64
dtypes: float64(2)
memory usage: 15.8 KB

In [7]:
df.corr()

                   Random variable 1  Random variable 2
Random variable 1           1.000000           0.017473
Random variable 2           0.017473           1.000000

**Exercise**: Create a data frame with at least three columns.

**Data handling**

Typically, a dataset is stored in a file. For example, one can export and store an excel sheet in a `.csv` file (CSV: comma-separated file). Similarly, we can store our data frame `df` in a `.csv` file with the `to_csv` function.

`df.to_csv("./datasets/data.csv", index=False)`

With this a new file (`data.csv`) is stored in the `./dataset/` folder that includes all values from the data frame.

When stored on github as in this course, you have not the rights to store the file in my repository.

In [8]:
def read_csv_from_github(url):
    import requests
    from io import StringIO
    response = requests.get(url)
    data = response.text
    return pd.read_csv(StringIO(data))


url = 'https://github.com/bgagl/ML_Individual_Differences/raw/5b70d36362172bb50d5be984e8c97526dda26bd2/datasets/data.csv'
data_from_github = read_csv_from_github(url=url)
data_from_github.head()

ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 2.8.3. See: https://github.com/urllib3/urllib3/issues/2168

**Exercise**: Store your new dataframe in the file `new_random_data.csv` and load it again.